config/routes.rb
Betahire::Application.routes.draw do
  resources :profiles
  devise_for :views
  devise_for :users, :controllers => { :registrations => "registrations" }
  root "pages#home" 
  get  "about" => "pages#about"
  get "edit" => "profiles#edit"
end

app/models/profile.rb
class Profile < ActiveRecord::Base
belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :location, presence: true
  validates :phone, presence: true

  has_many :profiles
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception

before_filter :update_sanitized_params, if: :devise_controller?

def update_sanitized_params
  devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation, :location, :phone)}
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def edit
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = current_user.profiles
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profiles = current_user.profiles.build
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.profiles.build(params[:profile].permit( :name, :email, :phone, :headline))

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update

    respond_to do |format|
      if @profile.update(params[:profile].permit( :name, :email, :phone, :headline))
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
     @profile = Profile.find(params[:id])
    end

    def correct_user
      @profile = current_user.profiles.find_by(id: params[:id])
      redirect_to profiles_path, notice: "Not authorized to edit this profile" if @profile.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params[:profile]
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_profile_path(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer">
		<div class="container">
	   		<a href="#">Home</a>
			<a href="#">About</a>
			<a href="#">Employers</a>
			<a href="#">FAQ</a>
			<a href="#">Terms of Use</a>
			<a href="#">Privacy</a>
			<a href="#">Contact Us</a>
		</div>
    		<br><p class="text-muted credit">©2013 Newco, LLC. All Rights Reserved.</p>
    	</div>
    </div>
</footer>

app/views/layouts/_header.html.erb
 <div class="index-header-image">
  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="container">
        <div class="navbar-brand"><%= link_to "BRAND", root_path %></div>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="container">
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "View Profile", profiles_path %></li>
            <li><%= link_to "Edit Profile", edit_profile_path(2) %></li>
            <li><%= link_to "Settings", root_path %></li>
          <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><a href="#">For Employers</a></li>
          <li><a href="#">Recommend</a></li>
          <li><a href="#">FAQ</a></li>
          <% end %> 
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
             <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><button type="button" class="btn btn-small btn-success"><%= link_to "Apply", new_user_registration_path %></button></li>
          <% end %>
        </ul>
      </div>
    </div><!-- /.navbar-collapse -->
  </nav>

app/views/layouts/_header2.html.erb
<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="container">
        <div class="navbar-brand"><%= link_to "BRAND", root_path %></div>
      </div>
    </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="container">
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><a href="#">For Employers</a></li>
          <li><a href="#">Recommend</a></li>
          <li><a href="#">FAQ</a></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><button type="button" class="btn btn-small btn-success"><%= link_to "Apply", new_user_registration_path %></button></li>
          <% end %>
        </ul>
      </div>
    </div><!-- /.navbar-collapse -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>		
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Betahire</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body class='<%= controller.controller_name %>'>

	<% if current_page?(root_path) == false %>
		<%= render 'layouts/header2' %>	
	<% end %>
	<% if current_page?(root_path) == true %>
		<%= render 'layouts/header' %>	
	<% end %>

	<div class="container">
		<% flash.each do |name, msg| %>
    		<%= content_tag(:div, msg, class: "alert alert-info") do %>
    		<%= msg %>
    		<button type="button" class="close" data-dismiss="alert">&times;</button>
    		<% end %>
		<% end %>
	</div>

	<%= yield %>

	<%= render 'layouts/footer' %>
 
</body>

</html>

app/views/pages/about.html.erb
<h1>Header</h1>

app/views/pages/home.html.erb
<div class="first-index-container">
	<div class="container">
		<div style="margin-top: 140px; height: 90px"> 
			<div class="header-h1">Propel Your Career to <br> the Next Level</div><br>
		</div>
		<div style="margin-top: 40px; height: 90px">
			<div class="header-h2">[Name] is the Leading Job Marketplace for Emerging<br>Finance Professionals</div>
		</div>
		<div class='col-lg-30 col-md-30 col-sm-30'>
			<div style="float:left; margin-right:30px">
				<%= link_to "Apply - It's Free", new_user_registration_path, class: "btn btn-huge btn-success" %> 
			</div>
				<%= link_to "Sign In", new_user_session_path, class: "btn btn-huge-two btn-default" %> 
		</div>
		<div style="float:left; margin-bottom:90px; margin-right: 105px">
			<br>
			<p>Investment Banking</p>
			<p>Hedge Funds</p>
		</div>
		<div class='col-lg-20 col-md-20 col-sm-20'>
			<br>
			<p>Private Equity & Venture Capital</p>
			<p>Corporate Development</p>
		</div>
	</div>
</div>

<div class="second-index-container">
	<div class="container">
		<div class="row">
	        <div class="col-lg-4">	
	        	<h1><span class="glyphicon glyphicon-ok-sign"></h1></span>
	         	<div class="header-h3">Members Only Benefits</div>
	         	<p>Our dedicated talent advocates will help craft your story and work with you from sign-up to offer signing.</p>

	        </div>
	        <div class="col-lg-4">
	       		<h1><span class="glyphicon glyphicon-search"></h1></span>
	          	<div class="header-h3">Personalized Search</div>
	          	<p>We help you find the right home from our network of the most prestigous employers in finance.</p>
	    	</div>
	    	<div class="col-lg-4">
	         	<h1><span class="glyphicon glyphicon-send"></h1></span>
	         	<div class="header-h3">An Easier Job Search</div>
	         	<p>No more mass emailing or endlessly searching job boards. Top employers are waiting to meet you today.</p>
	    	</div>
		</div>
	</div>
</div>

<div class="third-index-container">
	<div class="container">
		<div style="margin-top: 30px">
			<center><%= image_tag("macbook.png") %></center>
		</div>
		<div class="header-h4" style="margin-bottom:10px">
		<center><span class="glyphicon glyphicon-remove-sign">&nbsp;Your profile is hidden from current and past employers.</span></center>
		</div>
	</div>
</div>

<div class="fourth-index-container">
	<div class='container'>
		<div class='row'>
			<div class='col-lg-3 col-md-3 col-sm-3'>
				<h2 class='page-header normal-case'>Get Approved</h2>
					<p>Apply to be included in our marketplace.</p>
			</div>
			<div class='col-lg-3 col-md-3 col-sm-3'>
				<h2 class='page-header normal-case'>Get Offers</h2>
					<p>Receive offers with info about the company, role, and compensation.</p>
			</div>
			<div class='col-lg-3 col-md-3 col-sm-3'>
				<h2 class='page-header normal-case'>Interview</h2>
					<p>Choose which employers you want to interview with.</p>
			</div>
			<div class='col-lg-3 col-md-3 col-sm-3'>
				<h2 class='page-header normal-case'>Find Your Home</h2>
					<p>Accept and start your next journey!</p>
			</div>
		</div>
	<div class='row flush hidden-xs'>
		<div class='col-lg-12'>
			<img alt="How-it-works-progression" src="https://dmrxx81gnj0ct.cloudfront.net/assets/homepage/how-it-works-progression-acde1970c563cd4432e47bec6baf6701.png" />
		</div>
	</div>
	</div>
</div>

<div class="fifth-index-container">
	<div class='container'>
		<div class='row flush'>
			<div class='col-lg-offset-2 col-lg-10 col-md-offset-2 col-md-10 col-sm-offset-2 col-sm-10'>
				<h2 class='talent-advocate-headline page-header'>Your personal talent advocate helps you each step of the way</h2>
			</div>
		<div class='col-lg-2 col-md-2 col-sm-2 trent-container'>
<%=image_tag("Ryan.png") %>
<div class='trent-name'>
<h4>Ryan Aprill</h4>
<h5>Talent Advocate</h5>
</div>
</div>
<div class='col-lg-2 col-md-2 col-sm-2'>
<p>
<b>We help you&hellip;</b>
</p>
</div>
<div class='role col-lg-2 col-md-2 col-sm-2'>
<p>improve your profile to help tell your story</p>
</div>
<div class='role col-lg-2 col-md-2 col-sm-2'>
<p>prepare for interviews and call you an Uber</p>
</div>
<div class='role col-lg-2 col-md-2 col-sm-2'>
<p>understand the market and negotiate your offer</p>
</div>
<div class='role col-lg-2 col-md-2 col-sm-2'>
<p>write your resignation letter and book movers</p>
</div>
</div>
</div>
</div>

<div class="sixth-index-container">
	<div class="container">
		<div class='col-lg-8 col-md-8 col-sm-8'>
			<div class="header-h1" style="margin-top: 100px; margin-bottom:100px">Take your career to the next level,<br>create your profile now</div>
			</div>
			<div class='col-lg-3 col-md-3 col-sm-3' style="margin-top:105px; margin-bottom:100px">
				<button type="button" class="btn btn-success btn-huge-three">Apply</button> 
			</div>
		</div>
	</div>
</div>

<div class="seventh-index-container">
	<div class="container">
		<div style="margin-top: 50px">
			<div class='col-lg-2 col-md-2 col-sm-2'>
				<div class='pull-right'>
					<%=image_tag("Ryan.png") %>
				</div>
			</div>
		</div>
		
		<div style="margin-top: 40px">
			<div class='col-lg-9 col-md-9 col-sm-9'>
				<h2>"At the end of the week I had 8 offers, I was slightly overwhelmed but that was clearly the position I wanted to be in! It was just amazing. Great experience."</h2>
			</div>
		</div>
			<div style="margin-bottom: 300px">
				<div class='col-lg-9 col-md-9 col-sm-9'>
					<h4><b>Ryan Aprill, Investment Banker</b>
					<br>Houlihan Lokey, Chicago</h4>
				</div>
			</div>
		</div>
	</div>
</div> 

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
<%= f.label :name %><br>
<%= f.text_field :name %>
</div>

<div class="field">
<%= f.label :email %><br>
<%= f.text_field :email %>
</div>

<div class="field">
<%= f.label :phone %><br>
<%= f.text_field :phone %>
</div>

<div class="field">
<%= f.label :headline %><br>
<%= f.text_field :headline %>
</div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_form_edit.html.erb
<%= form_for (@profile) do |f| %>

<div class="field">
<%= f.label :name %><br>
<%= f.text_field :name %>
</div>

<div class="field">
<%= f.label :email %><br>
<%= f.text_field :email %>
</div>

<div class="field">
<%= f.label :phone %><br>
<%= f.text_field :phone %>
</div>

<div class="field">
<%= f.label :headline %><br>
<%= f.text_field :headline %>
</div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_form_new.html.erb
<%= form_for (@profiles) do |f| %>

<div class="field">
<%= f.label :name %><br>
<%= f.text_field :name %>
</div>

<div class="field">
<%= f.label :email %><br>
<%= f.text_field :email %>
</div>

<div class="field">
<%= f.label :phone %><br>
<%= f.text_field :phone %>
</div>

<div class="field">
<%= f.label :headline %><br>
<%= f.text_field :headline %>
</div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<div class="container">
<% @profiles.each do |profile| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
<td class="list_description">
<dl>
<dt><%= profile.name %></dt>
<dt><%= profile.email %></dt>
<dt><%= profile.phone %></dt>
<dt><%= profile.headline %></dt>
</dl>
</td>
<td class="list_actions">
<%= link_to 'Show', profile %><br/>
<%= link_to 'Edit', edit_profile_path(profile) %><br/>
<%= link_to 'Destroy', profile, method: :delete,
data: { confirm: 'Are you sure?' } %>
</td>
</tr>
<% end %>
</table>
<br />
</div>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<Div class="sign-up-container">
	<div class='container'>
			<div class='col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8'>
				<h1 class='page-header text-center'>Create Your Profile</h1>
				<%= render 'form_new' %>
			</div>
	
	</div>
</div>
	

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>